### PR TITLE
Add ability to use multiple accounts with the same server url

### LINKED ISSUE #88: Unable to use with multiple accounts
### Your environment

op-vscode version: 1.0.2

VS Code version: 1.71.2

CLI version: 2.7.1

OS: Ubuntu 22.04

## Steps to reproduce

1. Command Palette > `1password: choose acount` OR `1password: choose vault`
2. Choose one of the listed accounts.
  a. FWIW, both the listed acounts here have `my.1password.com` in light grey text displayed next to them.

## What happened?

vs code error toast popup:
`Error executing CLI command: found multiple accounts for filter "my.1password.com".`

## What did you expect to happen?

Be able to use one of the accounts. Be able to choose a vault belonging to one of the accounts

## Notes & Logs

```
["INFO" - 9:55:07 PM] Starting 1Password for VS Code.
["INFO" - 9:55:07 PM] Extension Version: 1.0.2.
["ERROR" - 9:55:15 PM] Error executing CLI command
```

### PR DESCRIPTION
**Pull request by dethancosta**
This PR changes the account flag used from the account URL to the account ID, allowing the user to switch between accounts both having a URL with, e.g., my.1password.com.

To test, simply open the command palette, choose either `1password: choose account` or `1password: choose vault`, choose the account/vault, and you should get the expected behaviour with no error message.

resolves #88

### CODE REVIEW

**Comment by interrobrian** [comment]
Any chance this could get merged soon? It would be tremendously helpful!

**Comment by james-beston** [comment]
Pleeeeeease!!

**Comment by TylerJMorg** [comment]
@jodyheavener 

Is it possible to take a look at this pr? Is there something were missing here?

It looks like the extension may be currently unusable for users with different accs on the same server (e.g., my.1password.com).

Many thanks!

**Comment by jodyheavener** [comment]
Sorry for the holdup, folks. Have tried this out and it all works great. 🚀

**Pull request merged**
