### PR TITLE
Fix compilation on fresh installs

### LINKED ISSUE #154: Development: Build fails on fresh installations
When trying to build the project locally on a fresh installation, with both `yarn watch` and `yarn compile`, esbuild fails with:
 ```sh
 esbuild Invalid option in build() call: "watch"
 ```
 This project was set up with `esbuild@0.15.x`, which dependabot has [upgraded](https://github.com/1Password/op-vscode/pull/119) to `0.17.6`. The problem is that [release v0.17.0](https://github.com/evanw/esbuild/releases/tag/v0.17.0) contains breaking changes in esbuild's incremental, watch, and serve APIs, so the `compile.ts` script is no longer valid.
 
 The solution is to either downgrade `esbuild` and tell dependabot to ignore it, or update the script to use the new APIs (and probably still tell dependabot to ignore it, or tell it not to upgrade minor version if possible).

### PR DESCRIPTION
**Pull request by vadimavdeev**
Local builds no longer work because esbuild has been upgraded to a backward-incompatible version. This PR updates `compile.ts` script to use the newer esbuild APIs. One difference between this and the previous version is that `console.log('[${name}] build succeeded')` will be called for every build, not only in watch mode.

Fixes #154

### CODE REVIEW

**Review by jodyheavener — COMMENTED** [review]
Hey @vadimavdeev, thanks so much for uncovering and open a PR for this issue! I just tried to give it a spin and it appears I'm still getting an error (using `yarn build` and `yarn watch`):

```
$ node -r esbuild-register compile.ts
✘ [ERROR] Invalid option in context() call: "watch"

    /Repositories/op-vscode/node_modules/esbuild/lib/main.js:255:12:
      255 │       throw new Error(`Invalid option ${where}: ${quote(key)}`);
          ╵             ^

    at checkForInvalidFlags (/Repositories/op-vscode/node_modules/esbuild/lib/main.js:255:13)
    at flagsForBuildOptions (/Repositories/op-vscode/node_modules/esbuild/lib/main.js:457:3)
    at buildOrContextContinue (/Repositories/op-vscode/node_modules/esbuild/lib/main.js:1009:9)
    at /Repositories/op-vscode/node_modules/esbuild/lib/main.js:983:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'll be happy to take a closer look at this during my next cycle, but I wanted to raise in case you had any ideas. Are you also experiencing this?

**Comment by vadimavdeev** [comment]
> Hey @vadimavdeev, thanks so much for uncovering and open a PR for this issue! I just tried to give it a spin and it appears I'm still getting an error (using `yarn build` and `yarn watch`):
> 
> ```
> $ node -r esbuild-register compile.ts
> ✘ [ERROR] Invalid option in context() call: "watch"
> 
>     /Repositories/op-vscode/node_modules/esbuild/lib/main.js:255:12:
>       255 │       throw new Error(`Invalid option ${where}: ${quote(key)}`);
>           ╵             ^
> 
>     at checkForInvalidFlags (/Repositories/op-vscode/node_modules/esbuild/lib/main.js:255:13)
>     at flagsForBuildOptions (/Repositories/op-vscode/node_modules/esbuild/lib/main.js:457:3)
>     at buildOrContextContinue (/Repositories/op-vscode/node_modules/esbuild/lib/main.js:1009:9)
>     at /Repositories/op-vscode/node_modules/esbuild/lib/main.js:983:11
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> I'll be happy to take a closer look at this during my next cycle, but I wanted to raise in case you had any ideas. Are you also experiencing this?

Yep, my bad. `watch: true` slipped through when I [put the error handling code back](https://github.com/1Password/op-vscode/pull/155/commits/1433d4082ad6c02e8bbdc46204cd64cda8fbdd9e). Should be fine now. Could you check again?

**Review by jodyheavener — APPROVED** [review]
That did it!

**Comment by jodyheavener** [comment]
Ah - apologies, we need all commits to be signed. Possible for you to squash this work and sign the commit? If you're new to commit signing we've made it [real easy](https://developer.1password.com/docs/ssh/git-commit-signing) to get set up 😏

**Comment by vadimavdeev** [comment]
> Ah - apologies, commits going into `main` need to be signed. Possible for you to squash this work and sign the commit? If you're new to commit signing we've made it [real easy](https://developer.1password.com/docs/ssh/git-commit-signing) to get set up 😏

Sure, let me do that.

**Comment by vadimavdeev** [comment]
Done. It was real easy indeed. 1Password's docs are excellent.

**Comment by jodyheavener** [comment]
Awesome, thank you so much for fixing this!

**Pull request merged**
